apiVersion: v1
kind: Service
metadata:
  name: rms-service
spec:
  selector:
    app: rms-docker-img
  ports:
    - protocol: TCP  # Standard protocol for most web applications
      port: 80       # Exposes port 80, the default HTTP port
      targetPort: 5050  # Port that the application listens on
  type: LoadBalancer  # Expose externally using a public IP
