version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16.20  # Specify Node.js version

jobs:
  backend-tests:
    executor: node-executor
    steps:
      - checkout  # Step 1: Checkout the repository
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Backend Tests
          command: npm run backend-test

workflows:
  version: 2
  test-workflow:
    jobs:
      - backend-tests
