version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16.20  # Specify Node.js version

jobs:
  backend-tests:
    executor: node-executor
    steps:
      - checkout  # Step 1: Checkout the repository
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Backend Tests
          command: npm run backend-test
      - run:
          name: Check Backend Coverage
          command: ls .nyc_output || echo "No coverage directory found."

  frontend-tests:
    executor: node-executor
    steps:
      - checkout  # Step 1: Checkout the repository
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Frontend Tests
          command: npm run frontend-test

workflows:
  version: 2
  test-workflow:
    jobs:
      - backend-tests
      - frontend-tests:
          requires:
            - backend-tests  # Run frontend tests after backend tests
