version: 2.1

jobs:
  backend-tests:
    machine: true  # Use CircleCI's machine executor
    steps:
      - checkout  # Step 1: Check out the repository
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Backend Tests
          command: npm run backend-test

workflows:
  version: 2
  test-workflow:
    jobs:
      - backend-tests
