version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.18  # Use a Node.js image
    working_directory: ~/repo

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  backend-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run backend tests
          command: npm run backend-test

  frontend-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Instrument frontend code
          command: npm run frontend-instrument
      - run:
          name: Run frontend tests
          command: npm run frontend-test

workflows:
  test-workflow:
    jobs:
      - install-dependencies
      - backend-tests:
          requires:
            - install-dependencies
      - frontend-tests:
          requires:
            - install-dependencies
