name: CI - Run Backend and Frontend Tests

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  backend-tests:
    runs-on: ubuntu-22.04  # Explicitly specify Ubuntu 22.04 to avoid future updates to ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Backend Tests
        run: npm run backend-test

      - name: Check Backend Coverage Directory
        run: ls .nyc_output || echo "Directory not found"

      - name: Upload Backend Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: .nyc_output/  # Ensure this path matches where nyc output is stored

  frontend-tests:
    runs-on: ubuntu-22.04  # Explicitly specify Ubuntu 22.04

    needs: backend-tests  # Run frontend tests only after backend tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Instrument Frontend Code
        run: npm run frontend-instrument

      - name: Run Frontend Tests
        run: npm run frontend-test

      - name: Check Frontend Coverage Directory
        run: ls .nyc_output || echo "Directory not found"

      - name: Upload Frontend Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage-report
          path: .nyc_output/  # Ensure this path matches where nyc output is stored

  notify:
    runs-on: ubuntu-22.04

    needs: [backend-tests, frontend-tests]

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            CI Workflow Status:
            Backend - ${{ needs.backend-tests.result }},
            Frontend - ${{ needs.frontend-tests.result }}
          body: |
            Hello,
            The CI workflow has completed with the following status:
            - Backend Tests: **${{ needs.backend-tests.result }}**
            - Frontend Tests: **${{ needs.frontend-tests.result }}**
            You can view the details here:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Best regards,  
            CI/CD System
          to: umarrashad2006@gmail.com
          from: umarrashad2006@gmail.com
