name: Docker Automation

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rms-docker-img:latest -f Dockerfile .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/rms-docker-img:latest

  notify:
    runs-on: ubuntu-22.04
    needs: docker-build-and-push

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            Docker Automation Status: 
            Docker - ${{ needs.docker-build-and-push.outcome }},

          body: |
            Hello,

            The Docker Automation workflow has completed with the following status:
            - Job Status: **${{ needs.docker-build-and-push.outcome }}**

            You can view the details here:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Best regards,  
            CI/CD System
          to: umarrashad2006@gmail.com
          from: umarrashad2006@gmail.com
