name: Kubernetes Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up kubectl using the kubeconfig secret
      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          if [ ! -s ~/.kube/config ]; then
            echo "Decoded kubeconfig is empty or invalid!" >&2
            exit 1
          fi
          kubectl config view  # Ensure kubeconfig is valid
          kubectl version --client
          kubectl cluster-info

      # Step 3: Check Kubernetes manifest files
      - name: Check manifest files
        run: |
          if [ ! -f rms-service.yaml ] || [ ! -f rms-deployment.yaml ]; then
            echo "Required Kubernetes manifest files are missing!" >&2
            exit 1
          fi

      # Step 4: Apply Kubernetes manifests (Service and Deployment)
      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f rms-service.yaml || sleep 5 && kubectl apply -f rms-service.yaml
          kubectl apply -f rms-deployment.yaml || sleep 5 && kubectl apply -f rms-deployment.yaml

      # Step 5: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/rms-deployment
          kubectl get all
          kubectl describe deployment rms-deployment  # Debugging: View deployment details
          kubectl logs -l app=rms-docker-img          # Debugging: View logs for the application

  notify:
    runs-on: ubuntu-22.04
    needs: deploy

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            Kubernetes Deployment Status: Kubernetes - ${{ needs.deploy.result }}
          body: |
            Hello,
            The Kubernetes Deployment workflow has completed with the following status:
            - Job Status: **${{ needs.deploy.outcome }}**
            You can view the details here:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Best regards,  
            CI/CD System
          to: umarrashad2006@gmail.com
          from: umarrashad2006@gmail.com
