name: Kubernetes Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Kubeconfig
        run: |
          cat ~/.kube/config
          kubectl config view


      # Step 2: Set up kubectl using the kubeconfig secret
      - name: Set up kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" | base64 -d > ~/.kube/config
          kubectl version --client
          kubectl cluster-info

      # Step 3: Apply Kubernetes manifests (Service and Deployment)
      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f rms-service.yaml
          kubectl apply -f rms-deployment.yaml

      # Step 4: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/rms-deployment
          kubectl get all
