name: Kubernetes Deployment with Datadog Monitoring

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          kubectl config view
          kubectl version --client
          kubectl cluster-info

      - name: Check manifest files
        run: |
          if [ ! -f rms-service.yaml ] || [ ! -f rms-deployment.yaml ]; then
            echo "Required Kubernetes manifest files are missing!" >&2
            exit 1
          fi

      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f rms-service.yaml || sleep 5 && kubectl apply -f rms-service.yaml
          kubectl apply -f rms-deployment.yaml || sleep 5 && kubectl apply -f rms-deployment.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/rms-deployment
          kubectl get all
          kubectl describe deployment rms-deployment
          kubectl logs -l app=rms-docker-img

  ## Deploy Datadog Agent for Monitoring
  datadog-agent:
    runs-on: ubuntu-22.04
    needs: deploy

    steps:
      - name: Deploy Datadog Agent in Kubernetes
        run: |
          kubectl create namespace datadog || true
          helm repo add datadog https://helm.datadoghq.com
          helm repo update
          helm upgrade --install datadog-agent datadog/datadog \
            --set datadog.apiKey=${{ secrets.DATADOG_API_KEY }} \
            --set datadog.site="datadoghq.com" \
            --set clusterAgent.enabled=true \
            --set kubeStateMetricsCore.enabled=true \
            --set logs.enabled=true \
            --set apm.enabled=true \
            --namespace datadog

  ## Enable Datadog Application Performance Monitoring (APM)
  datadog-apm:
    runs-on: ubuntu-22.04
    needs: datadog-agent
    steps:
      - name: Enable Datadog APM for Express App
        run: |
          kubectl set env deployment/rms-deployment \
            DD_AGENT_HOST="datadog-agent" \
            DD_TRACE_AGENT_PORT="8126" \
            DD_ENV="production" \
            DD_SERVICE="rms-express-app" \
            DD_VERSION="1.0"

  ## Notify and Send Monitoring Links
  notify:
    runs-on: ubuntu-22.04
    needs: datadog-apm
    steps:
      - name: Debug Needs Context
        run: |
          echo "Outcome: ${{ needs.datadog-apm.outcome }}"
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions Deployment Status with Datadog Monitoring"
          body: |
            Hello,
            
            The Kubernetes Deployment workflow has completed successfully! 🚀
            
            🔹 **Datadog Kubernetes Dashboard**: [View Here](https://app.datadoghq.com/kubernetes)
            🔹 **Datadog APM Tracing**: [View Here](https://app.datadoghq.com/apm)
            🔹 **Datadog Logs Monitoring**: [View Here](https://app.datadoghq.com/logs)

            View GitHub Actions Logs:  
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Best regards,  
            CI/CD System
          to: umarrashad2006@gmail.com
          from: umarrashad2006@gmail.com
